version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8000
    restart: always